# Lecture 4

In this lecture, we will to continue to learn NumPy `array`, and we will use flow control loops to manunipulate arrays.

## Review of NumPy array
`ndarray` is an arbitrary dimension set of variables of the *same type* (cf. `list` can be concatenate different types). In default, one entry of an array is a 64-bit float (a real number represented by 64 binary digit).
* Functions: `shape`, `reshape`, `arange`.

In [1]:
# always run this cell block first
import numpy as np

In [2]:
arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr[-1] # [] is used for array indexing, () is used as input of functions

9

## For loops

Syntax:
> for INDEX IN A SET:<br><br>
>       STUFF THAT WILL BE REPEATED IN EVERY ITERATION

## While loops

Very clever way to repeat actions. 

Syntax:
> while CONDITION FOR DOING THE NEXT ITERATION OF THE LOOP:
<br><br>
>       STUFF THAT WILL BE REPEATED IN EVERY ITERATION

In [12]:
# generate lst which is a list of integers from 0 to 9 using while
# code here
n = 0 # counter
lst = [] # initialize the list
while n < 100:
    lst.append(n+1) # the code to be executed if n < 10
    n = n + 1 # increase the counter by 1
while 99 < n <199:
    lst.append(199-n) # the code to be executed if n < 10
    n = n + 1 # increase the counter by 1
    
    
print(lst)    

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


## Example:  Checking for primeness
We want to write a function called `isprime` that checks if a number is prime. Returns `True` if number is prime, `False` otherwise. 

In [13]:
def isprime(n):
    # insert code here
    # we check all the divisor d < n whether n % d is 0
    # recall n % d is the modulo operation, 
    # which return the remainder of the division using divisor d

SyntaxError: unexpected EOF while parsing (<ipython-input-13-228a952b732d>, line 5)

In [14]:
isprime(10)

NameError: name 'isprime' is not defined

## Computing the sum of 1 to 100

In [15]:
# while loop version: generating an array
import numpy as np
arr = np.empty([100], dtype = 'int')
k = 1
while k <= 100:
    arr[k-1] = k
    k += 1
    
    

In [16]:
# for loop version

### Remark: Break and continue keywords

These are keywords:
* When the `break` was called, it stopped the loop without doing the print statement underneath. 
* `continue` skips the rest of the current looping of the loop but continues to loop as usual afterwards

<br>

### Good exercises (try by yourself):

* Using while loops, implement the integer division function `//` as `division(a,b)`. Make sure you are doing the negative number examples correctly. 
* Write a loop to print the first 100 prime numbers. 
* Make a list of all the prime numbers up to 1000 (using append to add elements)
* Write a function that will return the maximum element of a list
* Write a function that will return the sum of the elements of a list
* Write a function that takes two lists, and checks to see if they have at least one common element
* Estimate pi by adding the first 1000 terms in the formula: 
$$\frac{\pi}{4} = 1 - \frac13 + \frac15 - \frac17+ \cdots,$$ 
which comes from the Taylor expansion of $\arctan(x)$.
Write a code snippet to compare the answer to the built-in `math.pi`.

# Vectorization:

Instead of iterating along the indices, we can use built-in routine to make our execution more efficient.

In [7]:
arr = np.array(range(16))

In [8]:
arr = arr.reshape(4,4) + 1

In [9]:
arr.reshape(2,2,-1)    # if you put -1, it figures out what the shape should be

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [10]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [11]:
np.reshape(arr, (2,2,-1)) # -1 means unspecified

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [12]:
np.sum(arr)

136

In [13]:
np.mean(arr)

8.5

In [14]:
np.apply_along_axis()

TypeError: apply_along_axis() missing 3 required positional arguments: 'func1d', 'axis', and 'arr'

In [15]:
np.apply_along_axis(np.sum, 0, arr)

array([28, 32, 36, 40])

In [16]:
np.apply_along_axis(np.sum, 1, arr)

array([10, 26, 42, 58])

In [17]:
np.sum(arr, axis=1)

array([10, 26, 42, 58])