In [5]:
 B = random_matrix(FiniteField(7), 4, 4, algorithm='echelon_form', num_pivots=3);

In [6]:
B


[1 0 0 5]
[0 1 0 6]
[0 0 1 1]
[0 0 0 0]

In [154]:
A = matrix(FiniteField(5), 3, [1,1,2,4, 0, 4,3,2,   -2,2,-1,4]);

In [155]:
A

[1 1 2 4]
[0 4 3 2]
[3 2 4 4]

In [153]:
A1 = matrix(QQ, 3, [1,1,2,4, 0, 4,3,2,   -2,2,-1,4]);
A1

[ 1  1  2  4]
[ 0  4  3  2]
[-2  2 -1  4]

In [156]:
A1.rref()


[  1   0 5/4   0]
[  0   1 3/4   0]
[  0   0   0   1]

In [157]:
A.rref()

[1 0 0 1]
[0 1 2 3]
[0 0 0 0]

In [12]:
C = matrix(FiniteField(5), 3, [1,2,3, 0,1,3, 0,2,1]);

In [13]:
C

[1 2 3]
[0 1 3]
[0 2 1]

In [14]:
C.rref()

[1 0 2]
[0 1 3]
[0 0 0]

In [20]:
filename="C:/Users/Jun Li/Desktop/214/code.txt"
with open(filename) as f:
    mylist = f.read().splitlines() 
D=[int(y)  for x in mylist for y in x]
D

[1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,


In [34]:
S = matrix(FiniteField(2), 66, D);
S

66 x 9 dense matrix over Finite Field of size 2 (use the '.str()' method to see the entries)

In [35]:
S.str()


'[1 0 1 1 0 1 0 0 1]\n[0 1 1 0 0 1 1 0 0]\n[0 0 1 0 1 1 1 1 1]\n[0 1 0 0 0 0 0 0 0]\n[0 1 1 1 1 0 0 0 0]\n[0 1 1 1 0 1 1 0 1]\n[0 1 1 0 0 1 0 1 0]\n[1 1 0 0 1 1 0 1 0]\n[0 0 0 0 0 0 0 0 0]\n[1 0 1 1 1 0 0 1 0]\n[0 0 0 0 1 1 0 1 1]\n[1 1 0 0 1 1 0 1 0]\n[0 0 0 0 0 0 0 1 0]\n[1 0 0 0 0 1 0 0 1]\n[0 1 1 1 1 0 0 0 0]\n[0 0 0 0 0 0 0 0 0]\n[0 1 1 0 0 1 0 1 1]\n[0 0 1 1 1 1 1 1 1]\n[0 0 0 0 1 1 0 0 1]\n[1 1 0 1 0 1 1 0 0]\n[0 1 1 1 0 0 0 0 1]\n[0 0 0 0 0 0 0 0 0]\n[0 1 1 0 1 0 0 1 1]\n[0 0 0 0 1 1 0 0 1]\n[1 0 1 0 0 1 0 0 1]\n[0 1 0 1 0 1 1 0 0]\n[0 0 1 0 1 1 1 1 1]\n[0 1 1 0 1 0 0 1 0]\n[0 0 0 0 1 1 0 0 1]\n[1 0 1 0 0 1 0 1 1]\n[0 1 0 0 1 0 1 0 1]\n[0 0 0 1 1 1 0 1 0]\n[1 0 0 1 1 0 0 0 1]\n[0 0 0 0 1 0 0 0 0]\n[0 1 0 0 1 0 1 0 1]\n[1 0 0 1 1 0 1 0 0]\n[0 0 0 0 0 0 0 1 0]\n[1 0 1 0 0 1 0 0 1]\n[0 1 0 1 1 0 0 0 0]\n[0 0 0 0 0 0 0 0 0]\n[0 0 1 0 0 0 1 1 0]\n[0 1 1 1 1 0 0 0 0]\n[0 0 0 0 0 1 0 0 0]\n[0 1 1 0 1 0 0 1 1]\n[0 0 0 0 1 1 0 0 1]\n[1 0 1 1 0 1 0 0 1]\n[0 0 0 0 0 1 1 0 0]\n[0 0 1 0 1 1

In [23]:
string1 = "1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1 0 0 0 1"
print (string1)
print (string1.lstrip())

1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1 0 0 0 1
1 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 1 0 0 1 1 0 0 0 1


In [27]:
Hold = [string1.replace(" ", "")]
Hold
Hlist=list([int(y)  for x in Hold for y in x])
Hlist

[1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1]

In [29]:
Hbig =  matrix(FiniteField(2), 4, Hlist);
Hbig

[1 1 0 0 1 1 0 0 0]
[1 1 1 0 0 0 1 0 0]
[1 0 1 1 0 0 0 1 0]
[1 0 0 1 1 0 0 0 1]

TypeError: unsupported operand parent(s) for *: 'Full MatrixSpace of 4 by 9 dense matrices over Finite Field of size 2' and 'Full MatrixSpace of 66 by 9 dense matrices over Finite Field of size 2'

In [42]:
M = Hbig*S.T

In [57]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:52.5% !important; }</style>"))
M.str()

'[0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n[0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n[1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1]\n[1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0]'

In [58]:
 w = zero_vector(SR, 66*9) ; w

(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [60]:
Cr= matrix(FiniteField(2), 66,  w); Cr

66 x 9 dense matrix over Finite Field of size 2 (use the '.str()' method to see the entries)

In [61]:
Cr[0]

(0, 0, 0, 0, 0, 0, 0, 0, 0)

In [118]:
import numpy as np
a=np.array(M)
b=np.array(Hbig)
def crlist(M):
    results = []
    i = 0
    while i <= 65:
        ci=0
        for j in range(9):
            if  np.array_equal(a[:,i],  b[:,j]) :
                results.append(j+1)
                ci=1
                break
        if (ci==0):
            results.append(0)    
       # print(i)
       # print(results)
        i += 1
    return results
#print(crlist)
print(crlist(M))

[4, 3, 0, 2, 0, 7, 0, 0, 0, 9, 8, 0, 8, 3, 0, 0, 9, 4, 0, 2, 6, 0, 0, 0, 0, 4, 0, 9, 0, 8, 0, 0, 7, 5, 0, 9, 8, 0, 3, 0, 0, 0, 6, 0, 0, 4, 2, 0, 0, 0, 0, 1, 9, 0, 0, 0, 9, 9, 0, 0, 8, 0, 0, 0, 0, 8]


In [115]:
a[:,0]

array([0, 0, 1, 1], dtype=object)

In [126]:
c=np.array(crlist(M))
d=np.array(Cr)
i = 0
while i <= 65:
    if  c[i] != 0:
        d[i, c[i]-1 ]=1
    i= i+1
print(d)

[[0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0

In [128]:
F=d+S; F

array([[1, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 0, 1],
       [1, 1, 0, 0, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 1, 1, 1, 1],
       [0, 1, 1, 0, 1, 0, 0,

In [132]:
F[:,:5]

array([[1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1],
       [0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 1,

In [133]:
F[0,:5]

array([1, 0, 1, 0, 0], dtype=object)

In [136]:
type(F)

<class 'numpy.ndarray'>

In [144]:
letter_ind=[int(m,2) for m in [''.join([str(i) for i in x]) for x in F[:,:5]]]

In [151]:
import string
letters=[' ']
letters.extend(list(string.ascii_lowercase))
letters=np.array(letters)
letters

array([' ', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
       'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y',
       'z'], dtype='<U1')

In [152]:
''.join(letters[letter_ind])

'the only way to learn mathematics is to do mathematics paul halmos'

In [116]:
b[:,0]

array([1, 1, 1, 1], dtype=object)

In [86]:
v1= matrix(FiniteField(2), 9,  [1,0,0,1,1,0,1,0,1]);

In [47]:
Hbig*v1

[0]
[0]
[0]
[0]

In [48]:
v2= matrix(FiniteField(2), 9, [1,0,1,1,0,0,0,1,0]);

In [49]:
Hbig*v2

[1]
[0]
[0]
[0]

In [50]:
v3=  matrix(FiniteField(2), 9,  [1,1,0,1,1,1,1,0,1])
Hbig*v3

[0]
[1]
[0]
[0]